# Generated by Django 2.2.6 on 2019-10-29 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0003_remove_people_data_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='people_data',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='西元生日(ex:20120101)'),
            preserve_default=False,
        ),
    ]
