# Generated by Django 2.2.6 on 2019-10-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0005_auto_20191031_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='people_data',
            name='home_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
