# Generated by Django 2.2.6 on 2019-10-31 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0006_people_data_home_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people_data',
            name='home_link',
        ),
    ]
