# Generated by Django 2.2.6 on 2019-10-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0007_remove_people_data_home_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people_data',
            name='home_id',
            field=models.CharField(choices=[(1, '11'), (2, 'ee'), (3, 'eee')], max_length=10),
        ),
    ]
