# Generated by Django 2.2.6 on 2019-11-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0011_auto_20191103_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_data',
            name='use_file',
            field=models.FileField(upload_to='files', verbose_name='上傳檔案'),
        ),
    ]
