# Generated by Django 2.2.6 on 2019-11-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0012_auto_20191105_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_phone',
            field=models.CharField(max_length=100, verbose_name='家庭電話'),
        ),
    ]
