# Generated by Django 2.2.6 on 2019-11-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0013_auto_20191108_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity_data',
            options={'verbose_name_plural': '活動資料庫'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': '家庭資料庫'},
        ),
        migrations.AlterModelOptions(
            name='people_data',
            options={'verbose_name_plural': '香客資料庫'},
        ),
    ]
