# Generated by Django 2.2.6 on 2019-12-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0014_auto_20191112_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_data',
            name='name_id',
        ),
        migrations.AddField(
            model_name='activity_data',
            name='table_name',
            field=models.TextField(default='', verbose_name='請輸入要使用的欄位名稱,並已、符號分隔'),
            preserve_default=False,
        ),
    ]
