# Generated by Django 2.2.6 on 2020-01-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0016_people_data_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people_data',
            name='time',
        ),
    ]
