# Generated by Django 2.2.6 on 2020-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0018_people_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(max_length=1000)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '歷史紀錄',
            },
        ),
    ]
