# Generated by Django 2.2.6 on 2020-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0019_history_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people_data',
            name='birthday',
            field=models.CharField(max_length=20, verbose_name='西元生日'),
        ),
    ]
