# Generated by Django 2.2.6 on 2020-03-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0021_day_every_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name_plural': '法會日期'},
        ),
        migrations.AddField(
            model_name='every_day',
            name='Day_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='use_app.Day'),
        ),
        migrations.AlterField(
            model_name='every_day',
            name='date',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
