# Generated by Django 2.2.6 on 2020-07-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_app', '0022_auto_20200318_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='people_data',
            name='animal',
            field=models.CharField(default=12, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='every_day',
            name='five_lights',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='every_day',
            name='four_lights',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='every_day',
            name='one_lights',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='every_day',
            name='three_lights',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='every_day',
            name='two_lights',
            field=models.TextField(blank=True),
        ),
    ]
